[[constraint]]
  branch = "master"
  name = "github.com/kr/pretty"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "zombiezen.com/go/capnproto2"
  version = "2.17.0"

[prune]
  go-tests = true
  unused-packages = true
